substitutions:
  _REGION: europe-west1
  _AR_REPO: bkg-ai
  _SERVICE: opencode-ohmygosh
  _COMPUTE_REGION: europe-west1
  _CLOUD_RUN_SERVICE: opencode-app

steps:
  # Build mit Docker und Layer Caching
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-f"
      - "Dockerfile"
      - "--cache-from"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:latest"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$BUILD_ID"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:latest"
      - "."

  # Push images
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$BUILD_ID"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:latest"

  # Optional: Deploy to Cloud Run (uncomment to enable)
  # - name: "gcr.io/cloud-builders/gcloud"
  #   args:
  #     - "run"
  #     - "deploy"
  #     - "${_CLOUD_RUN_SERVICE}"
  #     - "--image"
  #     - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$BUILD_ID"
  #     - "--region"
  #     - "${_COMPUTE_REGION}"
  #     - "--platform"
  #     - "managed"
  #     - "--port"
  #     - "5003"
  #     - "--memory"
  #     - "4Gi"
  #     - "--cpu"
  #     - "2"
  #     - "--timeout"
  #     - "3600"
  #     - "--max-instances"
  #     - "3"
  #     - "--allow-unauthenticated"
  #     - "--set-env-vars"
  #     - "NODE_ENV=production,PORT=5003"

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$BUILD_ID"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:latest"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"
  substitutionOption: "ALLOW_LOOSE"

timeout: "1800s"
