steps:
  # Install dependencies using pnpm (since it's a pnpm workspace)
  - name: "gcr.io/cloud-builders/npm"
    args: ["install", "-g", "pnpm"]
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "install-opencode"]
    waitFor: ["-"]
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "install-oh-my-opencode"]
    waitFor: ["-"]
  # Run setup script (installs nvm, rust, conda, docker)
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args: ["./setup-environment.sh"]
  # Build Docker image if needed (assuming a Dockerfile exists)
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/opencode-workspace:$COMMIT_SHA", "."]
    # Note: Add a Dockerfile to the root if you want to build an image
  # Push the image to Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/opencode-workspace:$COMMIT_SHA"]
  # Deploy to Cloud Run (optional, uncomment if desired)
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args:
  #     - 'run'
  #     - 'deploy'
  #     - 'opencode-workspace'
  #     - '--image'
  #     - 'gcr.io/$PROJECT_ID/opencode-workspace:$COMMIT_SHA'
  #     - '--region'
  #     - 'europe-west1'
  #     - '--platform'
  #     - 'managed'
  #     - '--allow-unauthenticated'

# Options for the build
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"

# Timeout for the build
timeout: "1200s"
